site_name: The Pathfinder Society Chronicle Filler
theme: material
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
nav:
  - index.md
  - quickstart.md
  - installation.md
  - usage.md
  - extraction.md
  - templates.md
  - faq.md
  - troubleshooting.md
  - legal.md

