name: Go Test

on:
  push:
    paths: 
      - '**.go'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
          
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
        id: go


      -
        name: Build
        run: |
            cd pfscf
            go build -v .

      -
        name: Test
        run: |
            cd pfscf
            go test -v ./...
