name: Go Test

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
          
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
        id: go


      -
        name: Build
        run: go build -v .
        with:
          workdir: pfscf

      -
        name: Test
        run: go test -v ./...
        with:
          workdir: pfscf
